export const employees = [
  {
    ID: 1,
    FirstName: 'John',
    LastName: 'Heart',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
  {
    ID: 2,
    FirstName: 'Olivia',
    LastName: 'Peyton',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
  {
    ID: 3,
    FirstName: 'Robert',
    LastName: 'Reagan',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
  {
    ID: 4,
    FirstName: 'Greta',
    LastName: 'Sims',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
  {
    ID: 5,
    FirstName: 'Brett',
    LastName: 'Wade',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
  {
    ID: 6,
    FirstName: 'Sandra',
    LastName: 'Johnson',
    Email: 'example@vabiss.com',
    Password: '12345',
    Repassword: '12345',
  },
]
